services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: db-patients
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3307
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: db-patients
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 5000
    depends_on:
      - mysqldb
    networks:
      - internalnet
      
networks:
  internalnet:
    driver: bridge